language: java
jdk:
- oraclejdk8
- oraclejdk9
notifications:
  email: false
before_script:
- mvn clean
after_success:
- mvn clean cobertura:cobertura coveralls:report
script: mvn install -Dmaven.javadoc.skip=true -B -V
